//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SpotControl
{
    [Serializable]
    public class ActionMsg : Message
    {
        public const string k_RosMessageName = "spot_control_msgs/Action";
        public override string RosMessageName => k_RosMessageName;

        public string action;

        public ActionMsg()
        {
            this.action = "";
        }

        public ActionMsg(string action)
        {
            this.action = action;
        }

        public static ActionMsg Deserialize(MessageDeserializer deserializer) => new ActionMsg(deserializer);

        private ActionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "ActionMsg: " +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
